sudo: false
language: python
python:
  - '3.4'
services: postgresql
addons:
  postgresql: "9.3"
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'npm install npm -g'
  - 'npm install'
  - 'gem install sass'
  - 'gem install compass'
  - 'bower install'
  - psql -c 'create user afsbirez with superuser;' -U postgres
  - psql -c "alter user afsbirez with password 'afsbirez'" -U postgres
  - psql -c "alter user afsbirez createdb" -U postgres
  - psql -c 'create database afsbirez owner=afsbirez;' -U postgres
  - 'python manage.py migrate'
install:
  - apt-get install -y wkhtmltopdf
  - "pip install -r requirements.txt"
script:
- 'python manage.py test'
- 'node_modules/karma/bin/karma start'
