FORMAT: 1A
HOST: http://www.google.com

# SBIR-EZ
The [Small Business Innovation Research Program (SBIR)](http://en.wikipedia.org/wiki/Small_Business_Innovation_Research) is a U. S. Government program administered
by the Small Business Administration (SBA) to spur technological innovation in the small business sector, meet federal government needs and commercialize federally
funded investments. However, feedback from small business is that the SBIR program can be confusing and take a very long time before providing funding. SBIR-EZ is
a platform-as-a-service offering to allow companies to explore and apply for SBIR programs while leaving the business rules and user interface to be customized for
individual organizations to maximize utility to their users.

## Key Resources
* **Topics**: Put out by an agency 
* **Users**: May be a small business or government user
* **Applications**: Topic application packages submitted by small business.
* **Awards**: Several financial awards may be provided per topic but a company may receive only one award per topic. A company may be awarded many topics.


