FORMAT: 1A
HOST: http://api.data.gov

# SBIR-EZ
The U. S. Government's [Small Business Innovation Research (SBIR) Program](http://en.wikipedia.org/wiki/Small_Business_Innovation_Research) is administered
by the Small Business Administration (SBA) to spur technological innovation in the small business sector, meet federal government needs and commercialize federally
funded investments. However, navigating the SBIR program can be confusing and take a very long time before providing funding. SBIR-EZ Hypermedia API allows companies
to explore and apply for SBIR programs while leaving the business rules and user interface to be customized for
individual organizations to maximize utility to their users.

## Key Resources
* **Topics**: Requests put out by agencies to which small businesses reply
* **Users**: A system user; ay be a small business or government user
* **Applications**: Topic application packages submitted by small business.
* **Awards**: Several financial awards may be provided per topic but a company may receive only one award per topic. A company may be awarded many topics.

## Details
* **Entry Point:** https://api.data.gov
* **Required Header:** include ```SBIR-EZ-API-VERSION: 0``` as its own header line. This helps us ensure that what you get today is what you'll get tomorrow.
* **Response Media Types Supported:** [application/hal+json](http://stateless.co/hal_specification.html) (default)
* **Request Media Types Supported:** application/json (default), application/x-www-form-urlencoded, multipart/form-data
* **CRUD:** Use HTTP methods as follows:
    + **Create:** POST to a rel representing a collection ("applications") with either json or name-value paris in the body and corresponding Content-Type header
    + **Read:** GET to a single rel for an individual item ("application") or to a collection of items to retrieve a list ("applications")
    + **Update:** PUT and PATCH are both supported for updates. PUT has to include the entire document (links and timestamps are ignored). For PATCH,
    can just include one or more properties. Set the appropriate header type.
    + **Delete:** DELETE to remove a resource, where allowed.
* **Sort Order:** You can adjust the sort order of a colleciton response by appending ?order=<field1>,<field2>asc,<field3>desc
* **Pagination:** Although we have pre-built pagination links via the rels “first”, “prev”, “next”, and “last”, you can also control the number of items per page
with (? or &)limit=<limit>&offset=<offset> (the default limit is 20 and the max limit is currently 300).
* **Partial Resources:** If you only need a small portion of a resource (e.g. agency and description), specify fields by appending (? or &)fields=<field1>,<field2> to your href
* **Rels:** The following registered rels are used by our system: self, first, prev, next, and last. All other rels (in accordance with the [Web Linking RFC](http://tools.ietf.org/html/rfc5988))
are full URIs

# Group Topics
The solicitations put out by the Air Force for small businesses to respond to. This resource is *READ-ONLY*.

## GET /topics?{closed,q,start,limit,order}
Returns a collection of topics matching specified criteria
+ Parameters
    + closed = `false` (optional, string) ... True if closed topics should be included in the results, false otherwise.
        +Values
            + `true`
            + `false`
    + q (optional, string) ... A free-text string
    + start=`1` (optional, number) ... Starting index
    + limit=`20` (optional, number) ... Number of items to return. ***Maximum value is 200***
    + order=`asc` (optional, text) ... The order of collection response

        + Values
            + `asc`
            + `desc`
+ Response 200 (application/hal+json)

        {
          "_links": {
            "self": {
              "href": "/topics"
            },
            "curies": [
              {
                "name": "ea",
                "href": "http://sbirez.gsa.gov/rels/{rel}",
                "templated": true
              }
            ],
            "next": {
              "href": "/topics?start=21"
            },
            "ea:find": {
              "href": "/topics{?id}",
              "templated": true
            }
          },
          "_embedded": {
            "ea:topic": [
              {
                "_links": {
                  "self": {
                    "href": "/topics/361509"
                  }
                },
                "id": 361509,
                "title": "New Technology for Proteomics and Glycomics",
                "description": "Some description",
                "agency": "HHS",
                "release_date": 20110519,
                "open_date": "20110705",
                "close_date": "20140508",
                "days_to_close": 16,
                "status": "Open/Future"
              },
              {
                "_links": {
                  "self": {
                    "href": "/topics/361511"
                  }
                },
                "id": 361511,
                "title": "New Technology for Proteomics and Glycomics",
                "description": "some description",
                "agency": "HHS",
                "release_date": 20110519,
                "open_date": "20110705",
                "close_date": "20140508",
                "days_to_close": 16,
                "status": "Open/Future"
              },
              {
                "_links": {
                  "self": {
                    "href": "/topics/361465"
                  }
                },
                "id": 361465,
                "title": "NINDS SBIR Technology Transfer",
                "description": "Some description",
                "agency": "HHS",
                "release_date": 20110922,
                "open_date": "20111105",
                "close_date": "20140908",
                "days_to_close": 31,
                "status": "Open/Future"
              }
            ]
          }
        }

## GET /topics/{id}
Find a topic put out by an agency (solicitation)
+ Parameter
    + id (required, number) ... the unique identifier of the topic
+ Response 200 (application/hal+json)
    
        {
        "_links": {
          "self": {
            "href": "/topics/361465"
          }
        },
        "id": 361465,
        "title": "NINDS SBIR Technology Transfer",
        "description": "Some description",
        "agency": "HHS",
        "release_date": 20110922,
        "open_date": "20111105",
        "close_date": "20140908",
        "days_to_close": 31,
        "status": "Open/Future"
        }

# Group Awards
SBIR Phase I and II contracts awarded to small businesses. This resource is *READ-ONLY*.

## GET /awards?{q,company,ri,year,start,limit,order}
A collection of awarded contracts
+ Parameter
    + q (optional, text) ... Free-text search of the topic description
    + company (optional, text) ... Free-text search of the company name
    + ri (optional, text) ... Free-text search of the research institution name
    + year (optional, number) ... The year YYYY that the award occurred
    + start=`1` (optional, number) ... Starting index
    + limit=`20` (optional, number) ... Number of items to return. ***Maximum value is 200***
    + order=`asc` (optional, text) ... Sort order of collection response

        + Values
            + `asc`
            + `desc`
    
+ Response 200 (application/hal+json)

        {
          "_links": {
            "self": {
              "href": "/awards"
            },
            "curies": [
              {
                "name": "ea",
                "href": "http://sbirez.gsa.gov/rels/{rel}",
                "templated": true
              }
            ],
            "next": {
              "href": "/awards?start=21"
            },
            "ea:find": {
              "href": "/awards{?id}",
              "templated": true
            }
          },
          "_embedded": {
            "ea:award": [
              {
                "_links": {
                  "self": {
                    "href": "/awards/410031"
                  }
                },
                "id": 410031,
                "title": "Tailoring Titanium Microstructures for Reduced Oxygen Ingress during High Temperature Applications using a Novel Microstructure-Informatics Approach",
                "abstract": "ABSTRACT:  High temperature applications of titanium alloys are limited by their affinity to oxygen...",
                "agency": "USAF",
                "program": "SBIR",
                "phase": 2,
                "year": 2013,
                "company": "MRL Materials Resources LLC",
                "ri": ""
              },
              {
                "_links": {
                  "self": {
                    "href": "/awards/410007"
                  }
                },
                "id": 410007,
                "title": "Autonomous On-Board Control of Satellites for Space Superiority",
                "abstract": "ABSTRACT:  Future spacecraft could benefit from onboard planning and scheduling autonomy to effectively fulfill their missions...",
                "agency": "USAF",
                "program": "SBIR",
                "phase": 2,
                "year": 2013,
                "company": "Orbit Logic Incorporated",
                "ri": ""
              },
              {
                "_links": {
                  "self": {
                    "href": "/awards/409047"
                  }
                },
                "id": 409047,
                "title": "Naturalistic Neurocognitive Assessment Using Mobile Gaming Platforms",
                "abstract": "The neurocognitive health of U.S. service members plays a vital role in the defense of the United States...",
                "agency": "ARMY",
                "program": "STTR",
                "phase": 1,
                "year": 2013,
                "company": "Vista Partners LLC",
                "ri": "Institute for Creative Technologies"
              }
            ]
          }
        }

## GET /awards/{id}
An individual awarded contract.
+ Parameter
    + id (required, number) ... The unique identifier of the award
+ Response 200 (application/hal+json)

        {
            "_links": {
              "self": {
                "href": "/awards/409047"
              }
            },
            "id": 409047,
            "title": "Naturalistic Neurocognitive Assessment Using Mobile Gaming Platforms",
            "link": "http://www.sbir.gov/sbirsearch/detail/409047",
            "abstract": "The neurocognitive health of U.S. service members plays a vital role in the defense of the United States...",
            "agency": "ARMY",
            "program": "STTR",
            "phase": 1,
            "year": 2013,
            "company": "Vista Partners LLC",
            "ri": "Institute for Creative Technologies"
        }
        
# Profile CRUD [/profile]
Your profile.

## Get your profile [GET]
Get your profile
+ Response 200 (application/hal+json)

        {
          "_links": {
            "self": {
              "href": "/profile/409047"
            }
          },
          "id": "409047",
          "username": "testuser"
        }
        
## Update your profile [PUT]
Updates a topic application using patch partial representation
+ Request (application/json)

        {
        "id":"409047"
        }
+ Response 200 (application/hal+json)

        {
        "TO":"DO"
        }        

## Partial update your profile [PATCH]
Partially updates your profile using patch
+ Request

        {
        "TO":"DO"
        }
+ Response 200

        {
        "TO":"DO"
        }

# Group Applications
Your SBIR applications.

# Application Collection [/applications]
Resource representing a collection of applications to topics

    
## GET /applications?{q,start,limit,order}
Returns a collection of applications matching specified criteria
+ Parameters
    + q (optional, string) ... A free-text strings
    + start=`1` (optional, number) ... Starting index
    + limit=`20` (optional, number) ... Number of items to return. ***Maximum value is 200***
    + order=`asc` (optional, text) ... Sort order of collection response

        + Values
            + `asc`
            + `desc`
+ Response 200

        {
        "TO":"DO"
        }

# Application CRUD [/applications/{id}]

## Get an application [GET]
Gets an application by id
+ Parameters
    + id (required, nuber) ... The unique id
+ Response 200

        {
        "TO":"DO"
        }
        
## Create an application [POST]
Updates a topic application using patch partial representation
+ Parameters
    + id (required, number) ... the unique identifier for the application
+ Request

        {
        "TO":"DO"
        }
+ Response 200

        {
        "TO":"DO"
        }        

## Update an application [PUT]
Updates a topic
+ Parameters
    + id (required, number) ... the unique identifier for the application
+ Request

        {
        "TO":"DO"
        }
+ Response 200

        {
        "TO":"DO"
        }

## Partial update an application [PATCH]
Updates a topic application using patch partial representation
+ Parameters
    + id (required, number) ... the unique identifier for the application
+ Request

        {
        "TO":"DO"
        }
+ Response 200

        {
        "TO":"DO"
        }
        
## Delete an application [DELETE]
Updates a topic application using patch partial representation
+ Parameters
    + id (required, number) ... the unique identifier for the application
+ Request

        {
        "TO":"DO"
        }
+ Response 200

        {
        "TO":"DO"
        }
