"""empty message

Revision ID: 1871a2a2013
Revises: 50818048880
Create Date: 2015-02-09 12:44:18.340979

"""

# revision identifiers, used by Alembic.
revision = '1871a2a2013'
down_revision = '50818048880'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('references_reference_key', 'references', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('references_reference_key', 'references', ['reference'])
    ### end Alembic commands ###
