"""empty message

Revision ID: 214483484233
Revises: 36271309d1f6
Create Date: 2014-12-16 13:07:23.906735

"""

# revision identifiers, used by Alembic.
revision = '214483484233'
down_revision = '36271309d1f6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'todos_pkey')
    )
    ### end Alembic commands ###
