"""empty message

Revision ID: 2362a05f722a
Revises: 74cdf9a8b9
Create Date: 2015-02-02 13:08:28.083814

"""

# revision identifiers, used by Alembic.
revision = '2362a05f722a'
down_revision = '74cdf9a8b9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('full_text', pg.TSVECTOR(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'full_text')
    ### end Alembic commands ###
