"""empty message

Revision ID: 317fa92e432
Revises: 2c4498c1fe8
Create Date: 2015-02-03 10:48:12.982932

"""

# revision identifiers, used by Alembic.
revision = '317fa92e432'
down_revision = '2c4498c1fe8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phases_phase_key', 'phases', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('phases_phase_key', 'phases', ['phase'])
    ### end Alembic commands ###
