"""empty message

Revision ID: 3c71c2aac63
Revises: 317fa92e432
Create Date: 2015-02-04 11:41:56.099811

"""

# revision identifiers, used by Alembic.
revision = '3c71c2aac63'
down_revision = '317fa92e432'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_topics_full_text', 'topics', ['full_text'], unique=False, postgresql_using='gin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topics_full_text', table_name='topics')
    ### end Alembic commands ###
